etagere_index:
    path:     /
    defaults: { _controller: "BibliothequeBundle:Etagere:index" }
    methods:  GET

etagere_show:
    path:     /{id}/show
    defaults: { _controller: "BibliothequeBundle:Etagere:show" }
    methods:  GET

etagere_new:
    path:     /new
    defaults: { _controller: "BibliothequeBundle:Etagere:new" }
    methods:  [GET, POST]

etagere_edit:
    path:     /{id}/edit
    defaults: { _controller: "BibliothequeBundle:Etagere:edit" }
    methods:  [GET, POST]

etagere_delete:
    path:     /{id}/delete
    defaults: { _controller: "BibliothequeBundle:Etagere:delete" }
    methods:  DELETE

nb_exemplaire:
    path:     /{id}/nbExemplaire
    defaults: { _controller: "BibliothequeBundle:Etagere:testNbExemplaire" }
    methods:  [GET, POST]

delete_error:
    path:     /delete_error
    defaults: { _controller: "BibliothequeBundle:Etagere:delError" }
    methods:  GET