exemplaire_index:
    path:     /
    defaults: { _controller: "BibliothequeBundle:Exemplaire:index" }
    methods:  GET

exemplaire_show:
    path:     /{id}/show
    defaults: { _controller: "BibliothequeBundle:Exemplaire:show" }
    methods:  GET

exemplaire_new:
    path:     /new
    defaults: { _controller: "BibliothequeBundle:Exemplaire:new" }
    methods:  [GET, POST]

exemplaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "BibliothequeBundle:Exemplaire:edit" }
    methods:  [GET, POST]

exemplaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "BibliothequeBundle:Exemplaire:delete" }
    methods:  DELETE
