<?php

namespace BibliothequeBundle\Repository;

/**
 * ArchivageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivageRepository extends \Doctrine\ORM\EntityRepository
{
}
