<?php

namespace BibliothequeBundle\Repository;

/**
 * EmprunterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmprunterRepository extends \Doctrine\ORM\EntityRepository
{
}
