<?php

namespace BibliothequeBundle\Repository;

/**
 * ExemplaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExemplaireRepository extends \Doctrine\ORM\EntityRepository
{
    // on recupere les exemplaires empruntés qui ont un ID NULL
    // SI NULL c'est qu'il n'est pas emprunté
    public function findByLivreDispo(){
        $livre = $this->createQueryBuilder('e');
        $livre->leftJoin('e.emprunter','em')
            ->where('em.id IS NULL');
        return $livre->getQuery()->getResult();
    }
}
