<?php

namespace BibliothequeBundle\Repository;

/**
 * FaculteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaculteRepository extends \Doctrine\ORM\EntityRepository
{
}
