<?php

namespace BibliothequeBundle\Repository;

/**
 * RayonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RayonRepository extends \Doctrine\ORM\EntityRepository {

  public function getLivresRayon($id) {
    $query = $this->getEntityManager()->createQueryBuilder('l')
    ->select('l')
    ->from('BibliothequeBundle:Livre', 'l')
    ->innerJoin('BibliothequeBundle:Exemplaire', 'e', 'WITH', 'e.livre = l.id')
    ->innerJoin('BibliothequeBundle:Etagere', 'et', 'WITH', 'et.id = e.etagere')
    ->where('et.rayon = :idRayon')
    ->setParameter('idRayon', $id);

    return $query->getQuery()->getResult();
  }
  
}
