<?php

namespace BibliothequeBundle\Repository;

/**
 * RayonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RayonRepository extends \Doctrine\ORM\EntityRepository
{
}
