<?php

namespace BibliothequeBundle\Repository;

/**
 * ReserverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReserverRepository extends \Doctrine\ORM\EntityRepository
{
}
