BibliothequeBundle\Entity\Emprunter:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Repository\EmprunterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateDebut:
            type: datetime
        dateFin:
            type: datetime
    manyToOne:
        exemplaire:
            targetEntity: Exemplaire
            inversedBy: emprunter
            joinColumn:
                name: id_exemplaire
                referencedColumnName: id
                nullable: false
        emprunteur:
            targetEntity: Lecteur
            inversedBy: emprunter
            joinColumn:
                name: id_lecteur
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
