BibliothequeBundle\Entity\Emprunt:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Repository\EmpruntRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        datesortie:
            type: string
            length: 255
    lifecycleCallbacks: {  }
