BibliothequeBundle\Entity\Faculte:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Repository\FaculteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        designationFaculte:
            type: string
            length: 255
    oneToMany:
        etudiants:
            targetEntity: Lecteur
            mappedBy: faculte
            orphanRemoval: true
    lifecycleCallbacks: {  }
