BibliothequeBundle\Entity\Lecteur:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Repository\LecteurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomLecteur:
            type: string
            length: '20'
        prenomLecteur:
            type: string
            length: '50'
        cycleLecteur:
            type: integer
    oneToMany:
        reserver:
            targetEntity: Reserver
            mappedBy: lecteur
            cascade: [ persist ]
            orphanRemoval: true
        emprunter:
            targetEntity: Emprunter
            mappedBy: emprunteur
            cascade : [ persist ]
            orphanRemoval: true
    manyToOne:
        faculte:
            targetEntity: Faculte
            inversedBy: etudiants
            cascade: [ persist ]
    lifecycleCallbacks: {  }
