BibliothequeBundle\Entity\Lecteur:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Repository\LecteurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomLecteur:
            type: string
            length: '20'
        prenomLecteur:
            type: string
            length: '50'
        cycleLecteur:
            type: integer
    lifecycleCallbacks: {  }
