BibliothequeBundle\Entity\Livre:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Repository\LivreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255

    oneToOne:
        ecritPar:
            targetEntity: Auteur
            inversedBy: ecrit
            orphanRemoval: true
    lifecycleCallbacks: {  }
