BibliothequeBundle\Entity\Rayon:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Repository\RayonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        designation:
            type: string
            length: 255
    lifecycleCallbacks: {  }
