BibliothequeBundle\Entity\Reserver:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Repository\ReserverRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateReservation:
            type: datetime
    manyToOne:
        livre:
            targetEntity: Exemplaire
            inversedBy: reserver
            joinColumn:
                name : id_livre
                referencedColumnName: id
                nullable: FALSE
        lecteur:
            targetEntity: Lecteur
            inversedBy: reserver
            joinColumn:
                name: id_lecteur
                referencedColumnNam: id
                nullable: FALSE
    lifecycleCallbacks: {  }
