BibliothequeBundle\Entity\Theme:
    type: entity
    table: null
    repositoryClass: BibliothequeBundle\Repository\ThemeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        descriptionTheme:
            type: string
            length: 255
    oneToMany:
        rayon:
            targetEntity: Rayon
            mappedBy: theme_rayon
            orphanRemoval: true
    manyToMany:
        livre_theme:
            targetEntity: Livre
            mappedBy: theme_livre
            orphanRemoval: true
    lifecycleCallbacks: {  }
