bibliotheque_homepage:
    path:     /
    defaults: { _controller: BibliothequeBundle:Default:index }

bibliotheque_livre:
    resource: "@BibliothequeBundle/Resources/config/routing/livre.yml"
    prefix:   /livre

bibliotheque_auteur:
    resource: "@BibliothequeBundle/Resources/config/routing/auteur.yml"
    prefix:   /auteur

bibliotheque_theme:
    resource: "@BibliothequeBundle/Resources/config/routing/theme.yml"
    prefix:   /theme

bibliotheque_exemplaire:
    resource: "@BibliothequeBundle/Resources/config/routing/exemplaire.yml"
    prefix:   /exemplaire

bibliotheque_rayon:
    resource: "@BibliothequeBundle/Resources/config/routing/rayon.yml"
    prefix:   /rayon

bibliotheque_etagere:
    resource: "@BibliothequeBundle/Resources/config/routing/etagere.yml"
    prefix:   /etagere

bibliotheque_reserver:
    resource: "@BibliothequeBundle/Resources/config/routing/reserver.yml"
    prefix:   /reserver

bibliotheque_lecteur:
    resource: "@BibliothequeBundle/Resources/config/routing/lecteur.yml"
    prefix:   /lecteur

bibliotheque_faculte:
    resource: "@BibliothequeBundle/Resources/config/routing/faculte.yml"
    prefix:   /faculte

bibliotheque_emprunter:
    resource: "@BibliothequeBundle/Resources/config/routing/emprunter.yml"
    prefix:   /emprunter

bibliotheque_pret:
    path:     /pret
    defaults: { _controller: BibliothequeBundle:Pret:index }

bibliotheque_pret_liste:
    path:     /pret/liste
    defaults: { _controller: BibliothequeBundle:Pret:listePret }

bibliotheque_pret_listeParLivre:
    path:     /pret/liste/rechercheLivre
    defaults: { _controller: BibliothequeBundle:Pret:listePretParLivre }
    requirements:
        _method: POST

bibliotheque_pret_listeParLecteur:
    path:     /pret/liste/rechercheLecteur/{mot}
    defaults: { _controller: BibliothequeBundle:Pret:listePretParLecteur }

bibliotheque_pret_listeLivreDispo:
    path:     /pret/liste/livreDispo
    defaults: { _controller: BibliothequeBundle:Pret:consulteLivreDispo }
    requirements:
        _method: POST

bibliotheque_pret_ajoutPretLivre:
    path:     /pret/liste/livreDispo/ajoutPret
    defaults: { _controller: BibliothequeBundle:Pret:ajoutPretLivre }
    requirements:
        _method: POST

bibliotheque_pret_retour:
    path:     /pret/retour
    defaults: { _controller: BibliothequeBundle:Pret:retourPret }
    requirements:
        _method: POST

bibliotheque_pret_liste_horsDelais:
    path:     /pret/listeHorsDelais
    defaults: { _controller: BibliothequeBundle:Pret:listeHorsDelais }
