bibliotheque_livre:
    resource: "@BibliothequeBundle/Resources/config/routing/livre.yml"
    prefix:   /livre

bibliotheque_auteur:
    resource: "@BibliothequeBundle/Resources/config/routing/auteur.yml"
    prefix:   /auteur

bibliotheque_homepage:
    path:     /
    defaults: { _controller: BibliothequeBundle:Default:index }

bibliotheque_theme:
    resource: "@BibliothequeBundle/Resources/config/routing/theme.yml"
    prefix:   /theme
